'use client';

import { Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { AdminCard, AdminShell, Field, SectionTitle, StatusPill, createChangeHandler, fieldClassName, leadTone, makeId, textareaClassName, useAdmin, type DemoLead } from '../shared';

export function AdminLeadsPage() { return <AdminShell active="leads" title="Заявки" description="Заявки открываются отдельной страницей и не грузят редактор всего сайта."><LeadsContent /></AdminShell>; }
function LeadsContent() {
  const { data, updateData } = useAdmin();
  function addLead() { updateData((c) => ({ ...c, leads: [{ id: makeId('lead'), name: 'Новая заявка', phone: '+7', email: 'client@example.ru', program: 'Не выбрано', status: 'Новая', priority: 'Обычная', manager: 'Не назначен', note: '', createdAt: 'сейчас' }, ...c.leads] }), 'Добавлена заявка', 'Заявки'); }
  function updateLead<K extends keyof DemoLead>(id: string, key: K, value: DemoLead[K]) { updateData((c) => ({ ...c, leads: createChangeHandler(c.leads, id, key, value) }), 'Изменена заявка', 'Заявки'); }
  return <><SectionTitle eyebrow="CRM" title="Заявки с сайта" action={<Button type="button" onClick={addLead}><Plus className="h-4 w-4" /> Добавить</Button>} /><div className="grid gap-4">{data.leads.map((lead) => <AdminCard key={lead.id} className="grid gap-4"><div className="flex flex-wrap items-center justify-between gap-2"><StatusPill tone={leadTone(lead.status)}>{lead.status}</StatusPill><span className="text-xs font-bold text-slate-500">{lead.createdAt}</span></div><div className="grid gap-4 md:grid-cols-3"><Field label="Имя"><input className={fieldClassName()} value={lead.name} onChange={(event) => updateLead(lead.id, 'name', event.target.value)} /></Field><Field label="Телефон"><input className={fieldClassName()} value={lead.phone} onChange={(event) => updateLead(lead.id, 'phone', event.target.value)} /></Field><Field label="Email"><input className={fieldClassName()} value={lead.email} onChange={(event) => updateLead(lead.id, 'email', event.target.value)} /></Field></div><div className="grid gap-4 md:grid-cols-[1fr_0.45fr_0.45fr]"><Field label="Программа"><input className={fieldClassName()} value={lead.program} onChange={(event) => updateLead(lead.id, 'program', event.target.value)} /></Field><Field label="Статус"><select className={fieldClassName()} value={lead.status} onChange={(event) => updateLead(lead.id, 'status', event.target.value as DemoLead['status'])}><option>Новая</option><option>В работе</option><option>Ждёт ответа</option><option>Закрыта</option></select></Field><Field label="Менеджер"><input className={fieldClassName()} value={lead.manager} onChange={(event) => updateLead(lead.id, 'manager', event.target.value)} /></Field></div><Field label="Заметка"><textarea className={textareaClassName('min-h-24')} value={lead.note} onChange={(event) => updateLead(lead.id, 'note', event.target.value)} /></Field></AdminCard>)}</div></>;
}
